SELECT 
	P.ID,
	P.PRODUCT_NUMBER,
	B.ID as bin_id,
	B.ZONE,
	B.POSITION,
	B.SHELF,
	P.EDI_NUMBER
FROM 

	SMS.BIN B
	JOIN sms.SITE S ON B.DISTRIBUTOR_ID = S.DISTRIBUTOR_ID
	LEFT JOIN sms.stock st ON st.product_id = B.ID
	LEFT JOIN SMS.PRODUCT P ON P.ID = st.product_id

WHERE S.ID = 370 --SOUTHAVEN SITE

	AND P.PRODUCT_NUMBER IS NOT NULL
	

ORDER BY 
B.ID
